spring.application.name=book-review

# URL: Tuyệt đối KHÔNG ĐƯỢC có hbz_db_user:password ở trong này
spring.datasource.url=jdbc:postgresql://dpg-d7ltoom7r5hc739ljseg-a.oregon-postgres.render.com/hbz_db?sslmode=require

# Khai báo User và Pass ở 2 dòng riêng biệt này là đủ
spring.datasource.username=hbz_db_user
spring.datasource.password=Zb2Pb4dzZalCwSFDiUAb5gvC9wgN5Zex

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect